### ISSUE TITLE
多言語対応について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/CircularNotices#38]
CircularNoticeContentにlanguage_idがないので、多言語化できない感じですが、
回覧板は多言語化ないのでしょうか？
後々追加予定？

あと、回答データ（CircularNoticeTargetUser）は、多言語化するのでしょうかね。。。
これは、アンケートも同じですよね。
もくもく会で確認させてください。

**Comment by kteraguchi** [comment]
よくよく考えたら、回答データを多言語化すると集計データがおかしくなるのでダメですね。

**Comment by ClumsySmile** [comment]
origin_id を使うか key を使うかという方針が決定し次第、実装着手します。
