### ISSUE TITLE
回答内容登録処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/CircularNotices#42]
CircularNoticesController::Viewアクションに登録処理がありますが、
コントローラー分けたほうが良い気がしています。
CircularNoticesAnswerController::editアクションがCakePHPっぽいと思います。

**Comment by go-to** [comment]
修正しました。
https://github.com/NetCommons3/CircularNotices/commit/a8147f0ab474f4da914ffb913e869733550588e9
