### ISSUE TITLE
CircularNoticeBlockRolePermissionsControllerでFatal Error

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/CircularNotices#47]
https://github.com/NetCommons3/CircularNotices/commit/3a7111df41d1bf788a3f812cc3ba5af64f11cd13#diff-71854a4e65ad3ba541f79469c6b80e27

でFrameモデルを使用するように修正しています。
usesにないので、
Call to a member function findById() on a non-object  
のエラーが出ます。
そもそも、この処理いらない気がします。

https://github.com/NetCommons3/CircularNotices/blob/3a7111df41d1bf788a3f812cc3ba5af64f11cd13/Controller/CircularNoticeBlockRolePermissionsController.php#L86-L96
削除しても動いています。

**Comment by go-to** [comment]
修正完了につきクローズします。
https://github.com/NetCommons3/CircularNotices/commit/84d1656accc4121f42a34270ac9d4dc47c2e6f38
