### ISSUE TITLE
viewVars['userId']の削除

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/CircularNotices#66]
詳しくは、見てないのですが、下記の$userIdですが、viewVarsの中の$userIdを参照しているのでしたら、Current::read('User.id')に変えてください。

https://github.com/NetCommons3/CircularNotices/blob/master/View/CircularNotices/index.ctp#L111
https://github.com/NetCommons3/CircularNotices/blob/master/View/CircularNotices/view.ctp#L45

ちなみに、セットしているところは、下記です。
https://github.com/NetCommons3/NetCommons/blob/master/Controller/NetCommonsAppController.php#L158

**Comment by go-to** [comment]
https://github.com/NetCommons3/CircularNotices/commit/c50f59e73caa42ecc934147a4888f28abfe77f6f

**Comment by go-to** [comment]
修正完了につきクローズします。
