### ISSUE TITLE
回覧を削除する際、ループする必要ありますか？

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/CircularNotices#82]
回覧を削除する際、わざわざループしていますが、ループする必要ありますか？
https://github.com/NetCommons3/CircularNotices/blob/master/Model/CircularNoticeContent.php#L480-L490

**Comment by go-to** [comment]
処理を見直しました。
https://github.com/NetCommons3/CircularNotices/commit/9a1da5bde99f28d553cee63410249a64f080fdc1

新着削除処理の対応を行いました。
https://github.com/NetCommons3/CircularNotices/commit/00f72008c025e2a888bcb12a3449053dc68f8735

**Comment by go-to** [comment]
修正完了につきクローズします。
