### ISSUE TITLE
新着情報の削除処理の追加依頼

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/CircularNotices#83]
https://github.com/NetCommons3/CircularNotices/issues/82
このIssueのため、組み込めません。

こちらを参考に、
$this->contentKeyのセットとdeleteAllの第三引数をtrue（コールバックの有効）にしてください。
https://github.com/s-nakajima/Bbses/blob/master/Model/BbsArticle.php#L269-L270

**Comment by go-to** [comment]
対応しました。
https://github.com/NetCommons3/CircularNotices/commit/00f72008c025e2a888bcb12a3449053dc68f8735

**Comment by go-to** [comment]
修正完了につきクローズします。
