### ISSUE TITLE
無駄なHelperの定義ある

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/CircularNotices#86]
無駄なHelperの定義があります。
https://github.com/NetCommons3/NetCommons3/issues/221

Issueのほか、このHelperも使ってますか？
https://github.com/NetCommons3/CircularNotices/blob/master/Controller/CircularNoticesController.php#L55

一度、見直してください。

また、ログインしているユーザIDを使う場合は、AuthではなくCurrentを使ってください。
https://github.com/NetCommons3/CircularNotices/blob/master/Controller/CircularNoticesController.php#L299

**Comment by go-to** [comment]
対応しました。
https://github.com/NetCommons3/CircularNotices/commit/663f14cd10703c1cfbe3608da8182ddf01d526d1
